@APBD_3_HostAddress = http://localhost:5000

### Get all trips with their detailed countries
GET {{APBD_3_HostAddress}}/api/trips
Accept: application/json

### Get trips for client with ID 1
GET {{APBD_3_HostAddress}}/clients/1/trips
Accept: application/json

### Add a new client 
POST {{APBD_3_HostAddress}}/clients
Content-Type: application/json

{
  "firstName": "Mariusz",
  "lastName": "Kowlaski",
  "email": "mariusz@mariusz.pl",
  "telephone": "123456789",
  "pesel": "7505052566"
}

### Register client id 1 to trip id 2

PUT http://localhost:5000/clients/1/trips/2
Accept: application/json

### Delete the registered trip 2 for client id 1
DELETE http://localhost:5000/clients/1/trips/2
Accept: application/json
